import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
rows=[
('三秒警报','七十七条生命，一天之内消逝。二〇一一年七月二十二日，挪威接连遭遇两起袭击。城市里的爆炸声后，更大的悲剧正在逼近一座小岛。','0–3s: hard cut from blue emergency light reflecting in shattered office glass to a dropped umbrella on wet pavement. No strobe. 3–7s: civilian-level view of damaged Oslo government quarter, drifting dust, emergency workers moving. 7–12s: cut to an overcast Norwegian lake, a distant wooded island, water rippling. No nuclear cloud, no collapse, no bodies.'),
('凶手并非传说','实施袭击的，是安德斯·贝林·布雷维克。这不是所谓天才罪犯的传奇，而是一名极右翼极端分子，将仇恨变成现实暴力的恐怖袭击。','A sober investigative reconstruction. 0–5s: anonymous adult blond Norwegian man, early thirties, seen only from behind in an ordinary 2011 apartment corridor. 5–12s: empty austere room with closed laptop, curtains moving. No smile, no heroic lighting, no extremist insignia, no manifesto text.'),
('预谋留下的阴影','这场袭击并非临时起意。事前准备与极端思想交织，最终指向无辜的人。我们不复述他的宣言，也不展示作案方法，只追问悲剧如何发生。','0–6s: investigative evidence archive, a gloved adult archivist closes an unlabelled file, a wall clock moves. 6–12s: rain runs down an ordinary farmhouse window, empty interior beyond. No chemicals, explosives, weapon assembly, legible writings or tactical maps.'),
('十五点二十五分','下午三点二十五分，奥斯陆政府办公区发生爆炸。八人在这里遇难。街道被碎玻璃和烟尘笼罩，救援人员冲进现场，寻找仍然需要帮助的人。','Oslo government quarter reconstruction in July 2011. 0–4s: dust blows across broken office windows in a damaged but standing concrete building. 4–12s: two adult rescue workers move along a street with scattered glass and guide an unharmed adult away. No visible injuries, no mushroom cloud, no building collapsing.'),
('危险转向湖面','爆炸之后，危险没有结束。布雷维克离开奥斯陆，前往于特岛。那里正在举办工党青年组织的夏令营，岛上的人还不知道，袭击者正向他们靠近。','0–5s: anonymous unmarked ordinary 2011 passenger car travels on a Norwegian road; no police livery, no speeding spectacle. 5–12s: ferry landing across a grey lake toward a small forested island; rain ripples and trees sway. Observational, no tactical route or map.'),
('本该普通的一天','于特岛原本是一处相聚的地方。年轻人在这里参加夏令营，讨论政治，也憧憬未来。那天本该留下的是谈笑与回忆，而不是此后一生难忘的恐惧。','Overcast damp July Norwegian youth camp, not golden sunny weather. 0–6s: a few unidentifiable older teenagers and young adults talk quietly under a canopy, modest 2011 casual clothes. 6–12s: hands close a guitar case beside camp chairs; lake beyond. Subtle warm indoor light contrasted with cold exterior. No violence.'),
('被利用的信任','傍晚，袭击者穿着警察样式的制服，乘船抵达于特岛。他利用人们对警察的信任接近营地。最先遭到袭击的，包括营地负责人和一名警卫。','0–5s: ferry moors, a single anonymous adult in dark police-like clothing walks onto a jetty viewed from distant rear. 5–8s: two adult camp staff look toward the arrival. 8–12s: cut away to empty jetty as a rope swings. No visible gunshot, no injuries, no authentic identifiable victim likeness, no glamorized attacker.'),
('七十三分钟','下午五点二十一分左右，岛上的枪击开始。直到六点三十四分，警方才将袭击者逮捕。七十三分钟里，人们躲藏、求救，在恐惧中等待救援。','0–5s: shaky but legible view through empty wet woodland, distant running footsteps implied, no attacker viewpoint. 5–12s: two unidentifiable young adults crouch behind a large rock, one holding a 2011 mobile phone, breathing and moving naturally. No weapons or bodies, no attack choreography.'),
('湖水另一边的希望','有人躲进树林，有人跳进湖里，试图游向安全的地方。附近居民也驾船赶来救人。面对突如其来的暴力，普通人的援手，为求生者带来了一线希望。','0–5s: wide grey lake with distant adult swimmer silhouette, no drowning closeup. 5–12s: small civilian motorboat with adult rescuers approaches, one throws a flotation ring gently into water. Clear natural hand anatomy, no pulling complex tangled limbs, no shooting.'),
('不能混淆的数字','这一天，两起袭击共造成七十七人遇难。奥斯陆八人，于特岛六十九人。这不只是一串数字，而是一个个名字，以及再也无法完整团聚的家庭。','0–6s: subdued Oslo memorial, roses laid by adult mourners, no legible labels. 6–12s: quiet island shoreline, single rose in foreground, trees move in breeze. Restrained grief, no bodies or blood, no helicopter spectacle. Leave empty upper space for editorial numeric overlay added later.'),
('审判不是舞台','二〇一二年，案件进入审判。镜头不该成为凶手传播仇恨的舞台。法庭需要回答的，是他的刑事责任，以及社会应当如何防止危险再次发生。','Modern Norwegian courtroom reconstruction, 2012. 0–6s: wide shot of restrained wood-panelled courtroom, judges seated at plain desks. 6–12s: adult legal professional turns an unlabelled document. No raised arm salute, no speech by attacker, no American jury box, no wigs, no gavel.'),
('承担刑事责任','二〇一二年八月二十四日，法院作出判决。布雷维克被认定应当承担刑事责任，获判二十一年预防性拘留。注意，这不是二十一年后必然获释。','0–6s: judge in a sober modern Norwegian courtroom consults a folder, adult observers still but breathing. 6–12s: plain prison corridor door under muted window light, camera tracks toward it. No theatrics or identifiable real judges, no readable text, no gavel.'),
('二十一年不是倒计时','预防性拘留的关键，在于持续评估危险。如果法院认为他仍然威胁社会，拘留期限就可以延长。因此，二十一年并不是一张预先开好的出狱通行证。','0–6s: anonymous adult judicial officials review closed files at a simple desk, restrained procedural realism. 6–12s: prison security gate remains closed while a guard walks away. Metaphorical editorial reconstruction, no imaginary release scene, no smirking face.'),
('可能终身，不是自动终身','这种延长可以反复进行，因此可能形成终身拘禁。但可能终身，不等于自动关押到死。每一次延长，都需要依法审查，而不是用一句口号代替判决。','One continuous moving shot in a plain contemporary Norwegian secure corridor, anonymous adult guard checks a closed door and walks away; window light shifts gently, natural human motion. No dungeon, torture, chains, exaggerated solitary cell conditions, no claim this depicts an actual prison.'),
('记住谁','讲述这起案件，不该让凶手成为主角。更值得记住的，是遇难者、幸存者，以及伸出援手的人。面对极端暴力，你认为怎样才能更好地守护无辜者？','0–6s: adult hand places a rose with other flowers at a quiet lakeside remembrance, lake ripples and leaves move. 6–12s: camera rises gently over empty shoreline in subdued dawn light. Dignified hopeful ending, no villain portrait, no celebratory ending, leave central negative space for final editorial question.')]
style='12-second real moving cinematic AI reconstruction, not a static painting or Ken Burns slideshow. Match the supplied reference aesthetic: photoreal faces and fabric, muted olive green and tobacco brown, warm soft side light, deep soft shadows, restrained 35mm grain, shallow depth of field, premium historical-drama cinematography but accurate NORWAY 2011 or courtroom 2012 as specified, never 1940s costume. Landscape 16:9, no black bars. Two or three motivated cuts only. People and environment genuinely move; stable identity, realistic anatomy and object permanence. No generated captions, logos, UI, readable text, extremist symbols, gore, glorification or attack instructions. No speech; ambience only. '
story=[]
for i,(title,narr,shot) in enumerate(rows,1):
 story.append(dict(id=f'{i:02}',seconds='12',title=title,narration=narr,prompt=style+shot,visual_review='pending',narration_status='draft_pending_actual_footage'))
(ROOT/'storyboard.json').write_text(json.dumps(story,ensure_ascii=False,indent=2)+'\n')
md=['# 挪威七月二十二日：180 秒分镜与旁白草稿','', '15 × 12 秒；沿用参考图 16:9 横版。旁白须在看过实际生成画面后修订、实测配音时长；此稿不是已同步字幕。','']
for i,s in enumerate(story):
 md += [f"## {s['id']}｜{i*12:03d}–{(i+1)*12:03d} 秒｜{s['title']}",s['narration'],'',s['prompt'][len(style):],'']
(ROOT/'docs/分镜文案.md').write_text('\n'.join(md))
